Repository dcsaorg/Conformance-Gateway, pull requests merged in 2025-01, with the labels that each got.

#245 Update the EBL_PINT spec to match current swagger spec
  pint/src/main/resources/standards/pint/messages/pint-3.0.0-transport-document.json
  pint/src/main/resources/standards/pint/schemas/EBL_PINT_v3.0.0.yaml
Labels: Review effort [1-5]: 2

#247 SD-1931 Fix EBL conformance check issue
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
  ebl/src/test/java/org/dcsa/conformance/standards/ebl/checks/EBLChecksTest.java
Labels: Review effort [1-5]: 2

#248 SD-1939-Rename commoditySubreference to commoditySubReference in Booking and Ebl
  booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingChecks.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/model/PersistableCarrierBooking.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/models/CarrierShippingInstructions.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/CarrierScenarioParameters.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-2c2u1e.json
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-2c2u2e.json
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-amf.json
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-clad.json
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-dg.json
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-negotiable-bl.json
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-request.json
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-soc-references.json
Labels: Review effort [1-5]: 2

#249 SD-1933-Missing underscore and typo in SI status
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/ShippingInstructionsStatus.java
Labels: Review effort [1-5]: 1

#250 Use the proper name in the generated X.509 CN attribute
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/crypto/PayloadSignerFactory.java
Labels: Review effort [1-5]: 1

#251 SD-1932-Correct validation for number of copies/originals in ebl
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
  ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-request.json
  ebl/src/test/java/org/dcsa/conformance/standards/ebl/checks/EBLChecksTest.java
Labels: Review effort [1-5]: 2

#260 Rename internal attribute to make it less confusing
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/TDReceiveState.java
Labels: Review effort [1-5]: 1

#261 SD-1963: Use the RFC8785 approved Java library for JSON canonicalization
  ebl-issuance/pom.xml
  ebl/pom.xml
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/crypto/Checksums.java
Labels: Review effort [1-5]: 2

#236 SD-160: Add JIT 2.0 conformance standard implementation
  booking/src/test/java/org/dcsa/conformance/standards/booking/party/BookingStateTest.java
  core/src/main/java/org/dcsa/conformance/core/check/ConformanceCheck.java
  core/src/main/java/org/dcsa/conformance/core/check/UrlPathCheck.java
  core/src/main/java/org/dcsa/conformance/core/party/ConformanceParty.java
  core/src/main/java/org/dcsa/conformance/core/scenario/ScenarioListBuilder.java
  core/src/main/java/org/dcsa/conformance/core/toolkit/JsonToolkit.java
  jit/pom.xml
  jit/src/main/java/org/dcsa/conformance/standards/jit/JitComponentFactory.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/JitScenarioContext.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/JitScenarioListBuilder.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/JitStandard.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitCancelAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitDeclineAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitGetEventsAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitOOBTimestampAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitOOBTimestampInputAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitOmitPortCallAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitOmitTerminalCallAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitPortCallAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitPortCallServiceAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitTerminalCallAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitTimestampAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitVesselStatusAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/SupplyScenarioParametersAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/checks/JitChecks.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitClassifierCode.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitSchema.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitServiceTypeSelector.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitTimestamp.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitTimestampType.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/PortCallPhaseTypeCode.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/PortCallServiceEventTypeCode.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/PortCallServiceType.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/DynamicScenarioParameters.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitConsumer.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitFilterParameter.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitProvider.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitPublisher.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitRole.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitSubscriber.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/SuppliedScenarioParameters.java
  jit/src/main/resources/standards/jit/messages/jit-120-response.json
  jit/src/main/resources/standards/jit/messages/jit-200-port-call-request.json
  jit/src/main/resources/standards/jit/messages/jit-200-port-call-service-request.json
  jit/src/main/resources/standards/jit/messages/jit-200-terminal-call-request.json
  jit/src/main/resources/standards/jit/messages/jit-200-vessel-status-request.json
  jit/src/main/resources/standards/jit/schemas/JIT_v2.0.0.yaml
  jit/src/main/resources/standards/jit/schemas/jit-120-publisher.json
  jit/src/test/java/org/dcsa/conformance/standards/jit/checks/JitChecksTest.java
  jit/src/test/java/org/dcsa/conformance/standards/jit/model/PortCallServiceEventTypeCodeTest.java
  spring-boot/src/test/java/org/dcsa/conformance/manual/ManualScenarioTest.java
  spring-boot/src/test/java/org/dcsa/conformance/springboot/ConformanceApplicationTest.java
Labels: enhancement, Review effort [1-5]: 5

#263 SD-1995 Remove /v2 from endpoint URLs
  jit/src/main/java/org/dcsa/conformance/standards/jit/JitStandard.java
  jit/src/main/resources/standards/jit/schemas/JIT_v2.0.0.yaml
Labels: enhancement
