Repository dcsaorg/Conformance-Gateway, pull requests merged in 2025-09, with the labels that each got.

#375 SD-2432-updated the cs schema to 1.0.1
  commercial-schedules/src/main/resources/standards/commercialschedules/schemas/CS_v1.0.0.yaml
Labels: Review effort 2/5

#379 SD-2334: update booking schema
  booking/src/main/resources/standards/booking/schemas/BKG_v2.0.0.yaml
Labels: Review effort 4/5

#377 Sd 2398 create new booking scenarios
  booking/src/main/java/org/dcsa/conformance/standards/booking/BookingScenarioListBuilder.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/UC1_Shipper_SubmitBookingRequestAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingChecks.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/checks/ScenarioType.java
  booking/src/main/resources/standards/booking/messages/booking-api-2.0.0-non-operating-reefer.json
  booking/src/main/resources/standards/booking/messages/booking-api-2.0.0-routing-reference.json
  booking/src/main/resources/standards/booking/messages/booking-api-2.0.0-store-door-at-destination.json
  booking/src/main/resources/standards/booking/messages/booking-api-2.0.0-store-door-at-origin.json
  core/src/main/java/org/dcsa/conformance/core/check/JsonAttribute.java
Labels: Review effort 3/5

#386 Sd 2472 mandatory cutoff times
  booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingChecks.java
  booking/src/test/java/org/dcsa/conformance/standards/booking/checks/BookingChecksTest.java
Labels: Review effort 2/5

#382 SD-2418-Update/Correct EBL validations
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/UC1_Shipper_SubmitShippingInstructionsAction.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/CarrierTdNotificationPayloadRequestConformanceCheck.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EblChecks.java
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EblDatasets.java
  ebl/src/test/java/org/dcsa/conformance/standards/ebl/checks/EblChecksTest.java
Labels: Review effort 3/5

#367 SD-2373: implement ebl issuance error scenario
  ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/EblIssuanceComponentFactory.java
  ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/EblIssuanceScenarioListBuilder.java
  ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/action/IssuanceAction.java
  ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/action/IssuanceRequestErrorResponseAction.java
  ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/action/IssuanceRequestResponseAction.java
  ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/party/EblIssuanceCarrier.java
  ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/party/EblIssuancePlatform.java
  ebl-issuance/src/main/resources/standards/eblissuance/instructions/prompt-iss-reqres-error.md
  ebl-issuance/src/main/resources/standards/eblissuance/messages/eblissuance-v3.0.0-error-message.json
Labels: Review effort 3/5
