Repository dcsaorg/Conformance-Gateway, pull requests merged in 2025-07, with the labels that each got.

#343 SD-2273-Wrong nesting of PartyContactDetails in SI fix
  ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
Labels: Review effort 2/5

#340 Sd 2274 remove location type
  booking/src/main/java/org/dcsa/conformance/standards/booking/model/PersistableCarrierBooking.java
Labels: Review effort 2/5

#341 Sd 2268 cbrr after confirmed booking
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/AUC_Shipper_SendInvalidBookingAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/BookingAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/ShipperGetBookingAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/Shipper_GetAmendedBooking404Action.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/StateChangingBookingAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/UC11_Shipper_CancelBookingRequestAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/UC13ShipperCancelConfirmedBookingAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/UC3_Shipper_SubmitUpdatedBookingRequestAction.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/UC7_Shipper_SubmitBookingAmendment.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/action/UC9_Shipper_CancelBookingAmendment.java
  booking/src/main/java/org/dcsa/conformance/standards/booking/party/BookingShipper.java
  booking/src/test/java/org/dcsa/conformance/standards/booking/action/BookingActionTest.java
  booking/src/test/resources/schemas/dcsaorg-DCSA_BKG-2.0.0-resolved.yaml
  core/src/main/java/org/dcsa/conformance/core/check/UrlPathCheck.java
  core/src/test/java/org/dcsa/conformance/core/check/UrlPathCheckTest.java
Labels: Review effort 3/5

#342 SD-2158-Arrival Notice Conformance Initial scenarios and Checks
  arrival-notice/pom.xml
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/ANComponentFactory.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/ANScenarioListBuilder.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/AnStandard.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/action/ANAction.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/action/PublisherPostANAction.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/action/PublisherPostANNotificationAction.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/action/SubscriberGetANAction.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/checks/ANChecks.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/checks/ScenarioType.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/party/ANPublisher.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/party/ANRole.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/party/ANSubscriber.java
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/party/DynamicScenarioParameters.java
  arrival-notice/src/main/resources/standards/an/messages/arrivalnotice-api-100-get-response.json
  arrival-notice/src/main/resources/standards/an/messages/arrivalnotice-api-100-post-freetime-request.json
  arrival-notice/src/main/resources/standards/an/messages/arrivalnotice-api-100-post-freighted-request.json
  arrival-notice/src/main/resources/standards/an/messages/arrivalnotice-api-100-post-notification-request.json
  arrival-notice/src/main/resources/standards/an/messages/arrivalnotice-api-100-post-regular-request.json
  arrival-notice/src/main/resources/standards/an/schemas/AN_v1.0.0.yaml
  pom.xml
  sandbox/pom.xml
  sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceSandbox.java
  sandbox/src/main/java/org/dcsa/conformance/sandbox/SupportedStandard.java
  specifications/pom.xml
Labels: Review effort 4/5

#350 no-issue: cleanup pint
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/PintComponentFactory.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/PintScenarioListBuilder.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/PintInitiateTransferUnsignedErrorAction.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/PintTransferAdditionalDocumentFailureAction.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/ResetScenarioClassAction.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/ScenarioClass.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/checks/PintChecks.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/party/PintReceivingPlatform.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/party/PintSendingPlatform.java
Labels: Review effort 3/5

#351 Sd 2042 add error scenario v2
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/PintScenarioListBuilder.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/PintErrorResponseAction.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/party/PintReceivingPlatform.java
  pint/src/main/java/org/dcsa/conformance/standards/eblinterop/party/PintSendingPlatform.java
  pint/src/main/resources/standards/pint/messages/pint-3.0.0-error-message.json
  pint/src/main/resources/standards/pint/messages/pint-3.0.0-transport-document.json
Labels: Review effort 3/5

#353 SD-2233: Fix 2 scenarios related to FACS location type missing UNLOCODE
  ovs/src/main/java/org/dcsa/conformance/standards/ovs/OvsScenarioListBuilder.java
  ovs/src/main/resources/standards/ovs/messages/ovs-300-response.json
Labels: Review effort 2/5

#356 SD-2331-Removed type code validation from vessel voyage
  arrival-notice/src/main/java/org/dcsa/conformance/standards/an/checks/ANChecks.java
Labels: Review effort 2/5
