Repository dcsaorg/Conformance-Gateway, pull requests merged in 2025-03, with the labels that each got.

#283 Update Java dependencies
  cdk/pom.xml
  core/pom.xml
  ebl/pom.xml
  lambda/pom.xml
  pom.xml
  sandbox/pom.xml
  spring-boot/pom.xml
Labels: Review effort [1-5]: 1

#290 SD-2071 Booking: correct error message on cancellation in UC9 and improve prompt
  booking/src/main/java/org/dcsa/conformance/standards/booking/party/BookingCarrier.java
Labels: bug

#288 SD-2040 JIT: Test Error Response object too
  jit/src/main/java/org/dcsa/conformance/standards/jit/JitScenarioListBuilder.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitWrongTimestampAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitSchema.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitConsumer.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitPartyHelper.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitProvider.java
  jit/src/main/resources/standards/jit/messages/jit-200-error-message.json
Labels: enhancement

#292 SD-160 JIT: Update schema; improve OOB instruction
  jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitWrongTimestampAction.java
  jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitPartyHelper.java
  jit/src/main/resources/standards/jit/instructions/prompt-process-oob-request.md
  jit/src/main/resources/standards/jit/schemas/JIT_v2.0.0.yaml
Labels: enhancement

#291 SD-2053 Upgrade Web UI libraries, fixing esbuild and prismjs vulnerabilities
  webui/package-lock.json
Labels: enhancement

#294 SD-2045 CS: Add inline instructions
  commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/CsAction.java
  commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/CsGetPortSchedulesAction.java
  commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/CsGetRoutingsAction.java
  commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/CsGetVesselSchedulesAction.java
  commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/SupplyScenarioParametersAction.java
  commercial-schedules/src/main/resources/standards/commercialschedules/instructions/prompt-publisher-ssp.md
  commercial-schedules/src/main/resources/standards/commercialschedules/instructions/prompt-subscriber-get-secondpage.md
  commercial-schedules/src/main/resources/standards/commercialschedules/instructions/prompt-subscriber-get.md
  commercial-schedules/src/main/resources/standards/commercialschedules/instructions/prompt-subscriber-refresh-complete.md
Labels: Review effort 2/5

#295 SD-160 JIT 2.0: Update schema to latest
  jit/src/main/resources/standards/jit/schemas/JIT_v2.0.0.yaml
Labels: enhancement, Review effort 2/5

#297 Update Angular and fix vulnerabilities; update Java libs
  cdk/pom.xml
  ebl/pom.xml
  lambda/pom.xml
  pom.xml
  sandbox/pom.xml
  spring-boot/pom.xml
  webui/package-lock.json
  webui/package.json
Labels: Review effort 2/5
